<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>UltraWinBar</AssemblyName>
    <RootNamespace>UltraWinBar</RootNamespace>
    <Product>UltraWinBar</Product>
    <Title>UltraWinBar</Title>
    <RollForward>LatestMajor</RollForward>
    <TargetFrameworks>net6.0-windows;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>UltraWinBar.Program</StartupObject>
    <ApplicationManifest>Shell\app.manifest</ApplicationManifest>
    <AssemblyVersion>1.0.0.8</AssemblyVersion>
    <FileVersion>1.0.0.8</FileVersion>
    <ApplicationIcon>Assets\Resources\Brand\ultrawinbar.ico</ApplicationIcon>
    <PublishProfileRoot>$(MSBuildProjectDirectory)\Support\PublishProfiles\</PublishProfileRoot>
    <PublishProfileFullPath Condition="'$(PublishProfile)' != ''">$(PublishProfileRoot)$(PublishProfile).pubxml</PublishProfileFullPath>
    <Platforms>AnyCPU;x86;ARM64</Platforms>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
	<RuntimeHostConfigurationOption Include="Switch.System.Windows.Media.EnableHardwareAccelerationInRdp" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Support\tests\**\*.cs" />
    <Page Remove="Support\tests\**\*.xaml" />
    <None Include="Assets\Resources\**\*.*" Link="Resources\%(Filename)%(Extension)" TargetPath="Resources\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
    <None Include="Assets\Languages\**\*.xaml" Link="Languages\%(Filename)%(Extension)" TargetPath="Languages\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
    <None Include="Assets\Themes\**\*.xaml" Link="Themes\%(Filename)%(Extension)" TargetPath="Themes\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Resources\Desktop\desktop95-sm.png" />
    <None Remove="Assets\Resources\Desktop\desktop95-lg.png" />
    <None Remove="Assets\Resources\Brand\help.png" />
    <None Remove="Assets\Resources\Brand\ultrawinbar.ico" />
    <None Remove="Assets\Resources\Brand\FlatControls.xaml" />
    <None Remove="Assets\Resources\Effects\shader_invert.ps" />
    <None Remove="Assets\Resources\Start\Group01\start9x.png" />
    <None Remove="Assets\Languages\Group01\English.xaml" />
    <None Remove="Assets\Themes\Core\System.xaml" />
    <Page Remove="Shell\App.xaml" />
    <ApplicationDefinition Include="Shell\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" Version="3.1.1" />
    <PackageReference Include="ManagedShell" Version="0.0.358" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Resources\Desktop\desktop95-sm.png" />
    <Resource Include="Assets\Resources\Desktop\desktop95-lg.png" />
    <Resource Include="Assets\Resources\Brand\help.png" />
    <Resource Include="Assets\Resources\Effects\shader_invert.ps" />
    <Resource Include="Assets\Resources\Brand\FlatControls.xaml" />
    <Resource Include="Assets\Resources\Brand\ultrawinbar.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <EmbeddedResource Include="Assets\Resources\Calendar\HebrewMonths.json" LogicalName="UltraWinBar.Resources.HebrewMonths.json" />
    <Resource Include="Assets\Resources\Start\Group01\start9x.png" />
  </ItemGroup>

</Project>
